# Generated by Django 6.0.4 on 2026-05-10 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0013_alter_job_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Agreed price')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Currency')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Address')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='scheduled', max_length=20, verbose_name='Status')),
                ('employer_rating', models.PositiveSmallIntegerField(blank=True, help_text='Employer rates the worker (1-5)', null=True, verbose_name='Worker rating')),
                ('worker_rating', models.PositiveSmallIntegerField(blank=True, help_text='Worker rates the employer (1-5)', null=True, verbose_name='Employer rating')),
                ('employer_review', models.TextField(blank=True, default='')),
                ('worker_review', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_employer', to=settings.AUTH_USER_MODEL, verbose_name='Employer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='jobs.job', verbose_name='Job')),
                ('job_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='jobs.jobapplication', verbose_name='Job application')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_worker', to=settings.AUTH_USER_MODEL, verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='From status')),
                ('to_status', models.CharField(max_length=20, verbose_name='To status')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Status change',
                'verbose_name_plural': 'Status history',
                'ordering': ['-created_at'],
            },
        ),
    ]
