# Generated by Django 6.0.1 on 2026-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0003_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='workers', to='jobs.profession'),
        ),
    ]
