# Generated by Django 6.0.1 on 2026-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_full_name_remove_user_professions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='professions',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='region',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
