# Generated by Django 6.0.1 on 2026-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_workerprofile_professions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/'),
        ),
    ]
