# Generated by Django 6.0.1 on 2026-03-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_groups_alter_user_user_permissions'),
        ('jobs', '0011_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='worker_certificates/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profiles', to='jobs.profession'),
        ),
    ]
