# Generated by Django 6.0.4 on 2026-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workerprofile_certificate_workerprofile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('employer', 'Employer'), ('operator', 'Operator'), ('admin', 'Admin')], default='worker', max_length=20),
        ),
    ]
