# Generated by hand for the employer applicants API (distance_km).
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_set_can_hire_for_employers"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
