import polib

trans_ru = {
    "Uy xizmatlari eshigingizgacha": "Домашние услуги до вашей двери",
    "InTask orqali yaqin atrofdagi tekshirilgan ustalarni tez toping. Elektrik, santexnik, taʼmir, mebel yigʻish va boshqa xizmatlar.": "Быстро найдите проверенных мастеров поблизости через InTask. Электрик, сантехник, ремонт, сборка мебели и другие услуги.",
    "Tekshirilgan ustalar": "Проверенные мастера",
    "Manzil": "Адрес",
    "Toshkent, Yunusobod": "Ташкент, Юнусабад",
    "Qidiring: Konditsioner tozalash": "Поиск: Чистка кондиционера",
    "Usta bo'lish": "Стать мастером",
    "Kirish": "Войти",
    "Ro'yxatdan o'tish": "Регистрация",
    "Nima qidiryapsiz?": "Что вы ищете?",
    "Elektrik": "Электрик",
    "Santexnik": "Сантехник",
    "Konditsioner": "Кондиционер",
    "Tozalash": "Уборка",
    "Mebel yig'ish": "Сборка мебели",
    "Chuqur tozalash<br>va dezinfeksiya": "Глубокая уборка<br>и дезинфекция",
    "Uy ta'miri<br>va maishiy ish": "Ремонт дома<br>и бытовые работы",
    "daq": "мин",
    "reyting": "рейтинг",
    "tekshirilgan usta": "проверенный мастер",
    "buyurtma": "заказов",
    "Konditsioner xizmati": "Обслуживание кондиционеров",
    "Xizmat": "Услуга",
    "Uy tozalash": "Уборка дома",
    "soat": "час",
    "Jonli xarita": "Живая карта",
    "Toshkentda yaqin buyurtmalar": "Ближайшие заказы в Ташкенте",
    "Usta sifatida qo'shiling": "Присоединиться как мастер",
    "Buyurtmalar": "Заказы",
    "Ustalar": "Мастера",
    "Shahar bo'ylab joriy interaktiv xaritani bevosita kuzating.": "Отслеживайте текущую интерактивную карту по всему городу.",
    "Barchasi": "Все",
    "Ta'mir": "Ремонт",
    "Faol buyurtmalar": "Активные заказы",
    "tuman": "район",
    "o'rtacha": "в среднем",
    "haftalik buyurtmalar": "заказов в неделю",
    "to'lov vaqti": "время оплаты",
    "ro'yxat uchun": "для списка",
    "Hoziroq ariza berish": "Подать заявку сейчас",
    "Elektrik usta": "Мастер электрик",
    "Tez va ishonchli": "Быстро и надежно",
    "Oylik daromad": "Ежемесячный доход",
    "so'mgacha": "до сум",
    "Sifatli va kafolatli": "Качественно и с гарантией",
    "Toza va ozoda": "Чисто и аккуратно",
    "faol ustalar bilan birga": "вместе с активными мастерами",
    "O'zbekistondagi №1 tekshirilgan ustalar platformasi. Har qanday uy ishi — 15 daqiqada.": "Платформа №1 проверенных мастеров в Узбекистане. Любая работа по дому — за 15 минут.",
    "Xizmatlar": "Услуги",
    "Barcha xizmatlar": "Все услуги",
    "Biz haqimizda": "О нас",
    "Blog": "Блог",
    "Karyera": "Карьера",
    "Matbuot": "Пресса",
    "Biznes uchun": "Для бизнеса",
    "Yangi": "Новый",
    "Daromad kalkulyatori": "Калькулятор дохода",
    "Sertifikatsiya": "Сертификация",
    "Usta yordami": "Помощь мастера",
    "Yordam": "Помощь",
    "Savol-javob": "Вопросы и ответы",
    "Aloqa": "Контакты",
    "Xavfsizlik": "Безопасность",
    "Ilovani yuklab oling": "Скачайте приложение",
    "Qabul qilinadigan to'lovlar": "Принимаемые платежи",
    "Foydalanish shartlari": "Условия использования",
    "Maxfiylik siyosati": "Политика конфиденциальности",
    "Ommaviy oferta": "Публичная оферта",
    "Santexnik kerak": "Нужен сантехник",
    "Rozetka o'rnatish": "Установка розетки",
    "Chuqur tozalash": "Глубокая уборка",
    "UZS": "сум",
    "Siz ham": "Вы тоже",
    "usta bo'ling": "станьте мастером",
    "va 15 mln so'mgacha toping": "и зарабатывайте до 15 млн.",
    "InTask'da buyurtmalar oling, mijozlar bilan ishlang va daromadingizni oshiring. Ro'yxatdan o'tish bepul.": "Получайте заказы на InTask, работайте с клиентами и увеличивайте свой доход. Регистрация бесплатна."
}

trans_en = {
    "Uy xizmatlari eshigingizgacha": "Home services to your door",
    "InTask orqali yaqin atrofdagi tekshirilgan ustalarni tez toping. Elektrik, santexnik, taʼmir, mebel yigʻish va boshqa xizmatlar.": "Quickly find verified masters nearby through InTask. Electrician, plumber, repair, furniture assembly and other services.",
    "Tekshirilgan ustalar": "Verified masters",
    "Manzil": "Address",
    "Toshkent, Yunusobod": "Tashkent, Yunusabad",
    "Qidiring: Konditsioner tozalash": "Search: AC cleaning",
    "Usta bo'lish": "Become a master",
    "Kirish": "Login",
    "Ro'yxatdan o'tish": "Sign Up",
    "Nima qidiryapsiz?": "What are you looking for?",
    "Elektrik": "Electrician",
    "Santexnik": "Plumber",
    "Konditsioner": "AC",
    "Tozalash": "Cleaning",
    "Mebel yig'ish": "Furniture Assembly",
    "Chuqur tozalash<br>va dezinfeksiya": "Deep cleaning<br>and disinfection",
    "Uy ta'miri<br>va maishiy ish": "Home repair<br>and household work",
    "daq": "min",
    "reyting": "rating",
    "tekshirilgan usta": "verified master",
    "buyurtma": "orders",
    "Konditsioner xizmati": "AC Service",
    "Xizmat": "Service",
    "Uy tozalash": "Home Cleaning",
    "soat": "hour",
    "Jonli xarita": "Live map",
    "Toshkentda yaqin buyurtmalar": "Nearby orders in Tashkent",
    "Usta sifatida qo'shiling": "Join as a master",
    "Buyurtmalar": "Orders",
    "Ustalar": "Masters",
    "Shahar bo'ylab joriy interaktiv xaritani bevosita kuzating.": "Track the current interactive map directly across the city.",
    "Barchasi": "All",
    "Ta'mir": "Repair",
    "Faol buyurtmalar": "Active orders",
    "tuman": "districts",
    "o'rtacha": "average",
    "haftalik buyurtmalar": "weekly orders",
    "to'lov vaqti": "payment time",
    "ro'yxat uchun": "for listing",
    "Hoziroq ariza berish": "Apply right now",
    "Elektrik usta": "Master Electrician",
    "Tez va ishonchli": "Fast and reliable",
    "Oylik daromad": "Monthly income",
    "so'mgacha": "up to soum",
    "Sifatli va kafolatli": "Quality and guaranteed",
    "Toza va ozoda": "Clean and tidy",
    "faol ustalar bilan birga": "with active masters",
    "O'zbekistondagi №1 tekshirilgan ustalar platformasi. Har qanday uy ishi — 15 daqiqada.": "No.1 verified masters platform in Uzbekistan. Any home fix - in 15 mins.",
    "Xizmatlar": "Services",
    "Barcha xizmatlar": "All services",
    "Biz haqimizda": "About us",
    "Blog": "Blog",
    "Karyera": "Career",
    "Matbuot": "Press",
    "Biznes uchun": "For Business",
    "Yangi": "New",
    "Daromad kalkulyatori": "Income calculator",
    "Sertifikatsiya": "Certification",
    "Usta yordami": "Master support",
    "Yordam": "Help",
    "Savol-javob": "FAQ",
    "Aloqa": "Contact",
    "Xavfsizlik": "Security",
    "Ilovani yuklab oling": "Download app",
    "Qabul qilinadigan to'lovlar": "Accepted payments",
    "Foydalanish shartlari": "Terms of Use",
    "Maxfiylik siyosati": "Privacy Policy",
    "Ommaviy oferta": "Public Offer",
    "Santexnik kerak": "Need a plumber",
    "Rozetka o'rnatish": "Socket installation",
    "Chuqur tozalash": "Deep cleaning",
    "UZS": "UZS",
    "Siz ham": "You too",
    "usta bo'ling": "become a master",
    "va 15 mln so'mgacha toping": "and earn up to 15 mln soum",
    "InTask'da buyurtmalar oling, mijozlar bilan ishlang va daromadingizni oshiring. Ro'yxatdan o'tish bepul.": "Get orders on InTask, work with clients and increase your income. Registration is free."
}

def update_po(filepath, mapping):
    try:
        po = polib.pofile(filepath)
        for entry in po:
            msg = entry.msgid.replace("\\'", "'")
            if msg in mapping:
                entry.msgstr = mapping[msg]
            elif entry.msgid in mapping:
                entry.msgstr = mapping[entry.msgid]
        po.save()
        print(f"Successfully compiled injection into PO: {filepath}")
    except Exception as e:
        print(f"Error touching {filepath}: {e}")

update_po("locale/ru/LC_MESSAGES/django.po", trans_ru)
update_po("locale/en/LC_MESSAGES/django.po", trans_en)
print("Translating Dictionary Flush Complete!")
