# Generated by Django 6.0.1 on 2026-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='longitude',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lat',
            field=models.FloatField(default=41.2995, help_text='Latitude for map pin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='lng',
            field=models.FloatField(default=69.2401, help_text='Longitude for map pin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(help_text="Salary text, e.g. '5 mln so‘m+'", max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(help_text='Region key, e.g. buxoro, toshkent_city', max_length=50),
        ),
    ]
