# Generated by Django 6.0.1 on 2026-02-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_profession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude for map pin', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude for map pin', null=True),
        ),
    ]
