# Generated by Django 6.0.1 on 2026-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_contact_phone_job_description_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='job_photos/'),
        ),
    ]
