# Generated by Django 6.0.1 on 2026-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pay',
        ),
        migrations.AddField(
            model_name='job',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_currency',
            field=models.CharField(choices=[('UZS', "So'm (UZS)"), ('USD', 'Dollar (USD)')], default='UZS', max_length=3),
        ),
    ]
