# Generated by Django 6.0.1 on 2026-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_pay_job_pay_amount_job_pay_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pay_amount',
        ),
        migrations.AddField(
            model_name='job',
            name='pay_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_text',
            field=models.CharField(blank=True, default='', help_text="Old salary text (optional), e.g. '6–8 mln so‘m'", max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3),
        ),
    ]
