# Generated by Django 6.0.1 on 2026-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_pay_amount_job_pay_max_job_pay_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='job',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='job_photos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='job_photos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='job_photos/'),
        ),
    ]
