# Generated by Django 6.0.1 on 2026-03-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_photo_job_photo1_job_photo2_job_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.profession', verbose_name='Profession'),
        ),
    ]
