# Generated by Django 6.0.4 on 2026-05-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('doimiy', 'Doimiy'), ('vaqtinchalik', 'Vaqtinchalik'), ('soatlik', 'Soatlik'), ('kunlik', 'Kunlik')], max_length=20),
        ),
    ]
