# Generated by Django 6.0.4 on 2026-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('soatlik', 'Soatlik'), ('kunlik', 'Kunlik')], max_length=20),
        ),
    ]
