# Generated by Django 6.0.4 on 2026-06-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_rename_job_type_hourly_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
