# Generated by Django 6.0.4 on 2026-06-27 17:52

from django.db import migrations


# uz name -> (ru, en)
TRANSLATIONS = {
    "Yordamchi ishchi": ("Подсобный рабочий", "Helper"),
    "Quruvchi": ("Строитель", "Builder"),
    "Santexnik": ("Сантехник", "Plumber"),
    "Elektrik": ("Электрик", "Electrician"),
    "Payvandchi": ("Сварщик", "Welder"),
    "Haydovchi": ("Водитель", "Driver"),
    "Yuk tashuvchi": ("Грузчик", "Loader"),
    "Kuryer": ("Курьер", "Courier"),
    "Oshpaz": ("Повар", "Cook"),
    "Kichkintoylar qarovchisi": ("Няня", "Nanny"),
    "Tozalovchi": ("Уборщик", "Cleaner"),
    "Konditsioner ustasi": ("Мастер по кондиционерам", "AC technician"),
    "Mebel ustasi": ("Мебельщик", "Furniture maker"),
    "Bo'yoqchi": ("Маляр", "Painter"),
    "Bog'bon": ("Садовник", "Gardener"),
    "Usta": ("Мастер", "Handyman"),
    "Kompyuter ustasi": ("Компьютерный мастер", "Computer technician"),
    "Telefon ustasi": ("Мастер по телефонам", "Phone technician"),
    "Deraza ustasi": ("Оконный мастер", "Window technician"),
    "Qulflash ustasi": ("Мастер по замкам", "Locksmith"),
}


def populate(apps, schema_editor):
    Profession = apps.get_model("jobs", "Profession")
    for uz_name, (ru, en) in TRANSLATIONS.items():
        Profession.objects.filter(name=uz_name).update(name_ru=ru, name_en=en)


def unpopulate(apps, schema_editor):
    Profession = apps.get_model("jobs", "Profession")
    for uz_name in TRANSLATIONS:
        Profession.objects.filter(name=uz_name).update(name_ru="", name_en="")


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_profession_name_en_profession_name_ru'),
    ]

    operations = [
        migrations.RunPython(populate, unpopulate),
    ]