# Generated by Django 6.0.1 on 2026-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_populate_profession_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Human-readable address from the map picker (reverse-geocoded or typed)', max_length=255),
        ),
    ]
