# Generated by Django 4.2.30 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='house',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='landmark',
            field=models.CharField(blank=True, default='', help_text='Nearby landmark / orientir, free text', max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='street',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
