# Generated by hand for the employer applicants API (mobile 4d-1 / 4d-5).
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_job_district_job_house_job_landmark_job_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="workers_needed",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many workers are needed",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
