# Generated by Django 6.0.4 on 2026-06-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0013_alter_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='GMV')),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_assigned', models.PositiveIntegerField(default=0)),
                ('orders_accepted', models.PositiveIntegerField(default=0)),
                ('orders_completed', models.PositiveIntegerField(default=0)),
                ('assign_time_sum_sec', models.BigIntegerField(default=0)),
                ('assign_time_count', models.PositiveIntegerField(default=0)),
                ('new_clients', models.PositiveIntegerField(default=0)),
                ('returning_clients', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily metric',
                'verbose_name_plural': 'Daily metrics',
                'ordering': ['-date', 'district'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_0e09df_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'district'), name='uniq_dailymetric_date_district')],
            },
        ),
        migrations.CreateModel(
            name='DistrictProfessionDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('demand_count', models.PositiveIntegerField(default=0)),
                ('available_masters', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('tight', 'Tight'), ('gap', 'Gap')], default='ok', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_snapshots', to='jobs.profession', verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'District/profession demand',
                'verbose_name_plural': 'District/profession demand',
                'ordering': ['-date', 'district', 'profession'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_3ecb34_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'district', 'profession'), name='uniq_demand_date_district_profession')],
            },
        ),
    ]
